// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart';

/*
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
 */
// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZy9KMM5D1okt84RK_TDUQLT5BE0-G_cQ',
    appId: '1:713118506907:web:9bc9146ea7d1b5a3f10b3e',
    messagingSenderId: '713118506907',
    projectId: 'sportnigs',
    authDomain: 'sportnigs.firebaseapp.com',
    storageBucket: 'sportnigs.firebasestorage.app',
    measurementId: 'G-WG8M6KV1CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVe09N0vpwFherTpBwoTtLCiTF4ang8nw',
    appId: '1:713118506907:android:4dfd64bf5c531da4f10b3e',
    messagingSenderId: '713118506907',
    projectId: 'sportnigs',
    storageBucket: 'sportnigs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QANjVOM7Z2ACj6YSNE2SeLi960iKgO4',
    appId: '1:713118506907:ios:44d5cf87c7337a54f10b3e',
    messagingSenderId: '713118506907',
    projectId: 'sportnigs',
    storageBucket: 'sportnigs.firebasestorage.app',
    iosClientId: '713118506907-0klpusk6fhikne5g3vevd3hbdgl7fjet.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportnigs',
  );

}